# Generated by Django 3.2.4 on 2022-12-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентари',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('data_type', models.CharField(default='str', max_length=7, verbose_name='Тип данных')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='InventoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_tags', to='erm_tags.inventory', verbose_name='Инвентарные тэги')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_inventories', to='erm_tags.tag', verbose_name='Тэгированный инвентарь')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='tags',
            field=models.ManyToManyField(through='erm_tags.InventoryTag', to='erm_tags.Tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='commons.type', verbose_name='Тип'),
        ),
        migrations.AddConstraint(
            model_name='inventorytag',
            constraint=models.UniqueConstraint(fields=('inventory', 'tag'), name='inventory_tag_unique'),
        ),
    ]
