version: '3.10'
services:
  db:
    image: postgres:12.0-alpine
    shm_size: 1g
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=develop
      - POSTGRES_PASSWORD=develop
      - POSTGRES_DB=develop
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
