# Generated by Django 3.2.4 on 2022-12-26 19:08
from django.db import migrations

from apps.commons.utils.generate_random import generate_random_string


def create_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    type_model = apps.get_model('commons', 'Type')

    for i in range(100):
        type_model.objects.using(db_alias).create(
            name=generate_random_string(254),
        )

def delete_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    apps.get_model('commons', 'Type').objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_types, delete_types, ),
    ]
